version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm test || echo "Sem testes ainda"

  build_and_push_docker:
    docker:
      - image: cimg/node:18.17
      steps:
      - checkout

      - run:
          name: Show environment variable
          command: |
            echo "Environment: $ENVIRONMENT"

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build -t hugocarvalh0/devops-repo:$ENVIRONMENT .

      - run:
          name: Docker Login
          command: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push image to DockerHub
          command: docker push hugocarvalh0/devops-repo:$ENVIRONMENT

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - build_and_push_docker:
          requires:
            - build
